Create VarInitDemo.java
VasilevaVeronika/java-learning pull request #13
Opened 2021-10-07 14:23 UTC by VasilevaVeronika

2021-10-07 17:31 UTC, romer533 requested changes

2021-10-07 17:31 UTC, romer533 commented on src/com/veronika/part_2/VarInitDemo.java
> +}
No newline at end of file

2021-10-07 17:31 UTC, romer533 commented on src/com/veronika/part_2/VarInitDemo.java
> +        for (x = 0; x < 3; x++) {
Можно использовать следующую конструкцию: `for (int x = 0, x < 3, x++) { ??? }`

2021-10-15 03:26 UTC, VasilevaVeronika commented on src/com/veronika/part_2/VarInitDemo.java
> +        for (x = 0; x < 3; x++) {
changed

2021-10-18 06:34 UTC, romer533 requested changes

2021-10-18 06:34 UTC, romer533 commented on src/com/veronika/part_2/VarInitDemo.java
> +}
не исправила

2021-10-19 15:20 UTC, romer533 requested changes

2021-10-19 15:20 UTC, romer533 commented on src/com/veronika/part_2/VarInitDemo.java
> +}
No newline at end of file!!!!!!!!!!!!!!
3ий раз пишу, переведи наконец-то эту фразу в переводчике, что она обозначает?

2021-10-20 14:23 UTC, romer533 approved these changes

2021-10-20 15:48 UTC, merged