Create guess_2.java
VasilevaVeronika/java-learning pull request #25
Opened 2022-01-05 11:51 UTC by VasilevaVeronika

2022-01-05 17:33 UTC, romer533 requested changes

2022-01-05 17:33 UTC, romer533 commented on src/part_3/guess_2.java
> +public class guess_2 {
Неправильное наименование класса

2022-01-10 07:19 UTC, romer533 commented on src/part_3/guess_2.java
> +public class guess_2 {
Fixed?

2022-01-10 13:50 UTC, VasilevaVeronika commented on src/part_3/guess_2.java
> +public class guess_2 {
Fixed

2022-01-11 15:01 UTC, romer533 requested changes

2022-01-11 15:01 UTC, romer533 commented on src/part_3/guess2.java
> +public class guess2 {
Неправильное наименование класса

2022-01-28 10:52 UTC, merged