Create HelpJava.java
VasilevaVeronika/java-learning pull request #30
Opened 2022-01-06 13:57 UTC by VasilevaVeronika

ой отхвачу я за эту справочную систему,зато креативно:)

2022-01-10 07:27 UTC, romer533 requested changes

2022-01-10 07:27 UTC, romer533 commented on src/com/veronika/part_3/HelpJava.java
> +        char choice;
Почему тут тип char?

2022-01-10 07:27 UTC, romer533 commented on src/com/veronika/part_3/HelpJava.java
> +                for (byte i = 0; i < 10; i++) {
От куда тут взялся byte?)

2022-01-10 07:27 UTC, romer533 commented on src/com/veronika/part_3/HelpJava.java
> +                for (byte i = 0; i < 5; i++) {
От куда тут взялся byte?)

2022-01-10 07:27 UTC, romer533 commented on src/com/veronika/part_3/HelpJava.java
> +                System.out.print("Запрос не найден.");
Чтобы не писать многочисленные `System.out.print` можно описать метод `print` который будет принимать `message` и выводить на консоль значение

`private void print(String message) = System.out.print(message);`

Теперь этот метод можно везде использовать и будет выглядеть красивее

2022-01-10 13:53 UTC, VasilevaVeronika commented on src/com/veronika/part_3/HelpJava.java
> +                for (byte i = 0; i < 5; i++) {
Ну у меня нет огромных цифр,которые бы не влезли бы в byte 
Разве это ошибка?

2022-01-10 14:05 UTC, VasilevaVeronika commented on src/com/veronika/part_3/HelpJava.java
> +                System.out.print("Запрос не найден.");
так, это мне так вписывать за место 57 строки?

2022-01-11 15:03 UTC, romer533 commented on src/com/veronika/part_3/HelpJava.java
> +                for (byte i = 0; i < 5; i++) {
Излишняя оптимизация, она тут не нужна, в циклах всегда используется int

2022-01-11 15:03 UTC, romer533 commented on src/com/veronika/part_3/HelpJava.java
> +                System.out.print("Запрос не найден.");
Нет, это делается отдельным методом и используется везде

2022-01-28 12:07 UTC, merged