Create ForVar.java
VasilevaVeronika/java-learning pull request #37
Opened 2022-01-11 14:21 UTC by VasilevaVeronika

2022-01-11 15:05 UTC, romer533 requested changes

2022-01-11 15:05 UTC, romer533 commented on src/com/veronika/part_3/ForVar.java
> +            fact *= i;
Это так было в книге?
Тут же всегда будет fact = 0?

2022-01-11 15:05 UTC, romer533 commented on src/com/veronika/part_3/ForVar.java
> +        System.out.println("Факториал: + fact");
сразу видно, программу не запускала

2022-01-11 15:08 UTC, VasilevaVeronika commented on src/com/veronika/part_3/ForVar.java
> +            fact *= i;
да,в книге так и написано

2022-01-11 15:09 UTC, VasilevaVeronika commented on src/com/veronika/part_3/ForVar.java
> +        System.out.println("Факториал: + fact");
чёй то,запускала я

2022-01-11 15:20 UTC, romer533 commented on src/com/veronika/part_3/ForVar.java
> +        System.out.println("Факториал: + fact");
То есть результат в консоли в виде: "Факториал: + fact" - тебя полностью устраивал?

2022-01-11 15:21 UTC, romer533 commented on src/com/veronika/part_3/ForVar.java
> +            fact *= i;
Можешь пожалуйста скинуть скриншот с куском этого кода из книги?

2022-01-11 15:22 UTC, romer533 commented on src/com/veronika/part_3/ForVar.java
> +        System.out.println("Факториал: + fact");
И нет слова "чёй то", есть "С чего вдруг" и "Почему" ну край "Чего это"

2022-01-13 05:47 UTC, VasilevaVeronika commented on src/com/veronika/part_3/ForVar.java
> +        System.out.println("Факториал: + fact");
Fixed

2022-01-14 05:41 UTC, romer533 requested changes

2022-01-16 15:13 UTC, VasilevaVeronika commented on src/com/veronika/part_3/ForVar.java
> +        System.out.println("Факториал: + fact");
Fixed

2022-01-28 10:54 UTC, merged