Create WhileDemo.java
VasilevaVeronika/java-learning pull request #38
Opened 2022-01-11 14:51 UTC by VasilevaVeronika

2022-01-11 15:06 UTC, romer533 requested changes

2022-01-11 15:06 UTC, romer533 commented on src/com/veronika/part_3/WhileDemo.java
> +        ch++;
Сразу видно, программу не запускала, отрабатывает не корректно

2022-01-12 12:17 UTC, VasilevaVeronika commented on src/com/veronika/part_3/WhileDemo.java
> +        ch++;
fixed

2022-01-12 15:49 UTC, romer533 approved these changes

2022-01-13 05:43 UTC, merged