Create CharAriDemo.java
VasilevaVeronika/java-learning pull request #4
Opened 2021-09-23 08:20 UTC by VasilevaVeronika

2021-09-23 09:01 UTC, romer533 commented
Первое: название ветки, соблюдай стандарты: все символы строчные, никаких пробелов, вместо них `_`

2021-09-23 09:03 UTC, romer533 reviewed
Need to fix

2021-09-23 09:03 UTC, romer533 commented on src/CharAriDemo.java
> +        System.out.println("теперь ch содержит" + ch);
Нет пробела между строкой и значением

2021-09-23 09:03 UTC, romer533 commented on src/CharAriDemo.java
> +        System.out.println("теперь ch содержит" + ch);
Нет пробела между строкой и значением

2021-09-23 09:03 UTC, romer533 commented on src/CharAriDemo.java
> +        System.out.println("теперь ch содержит" + ch);
Нет пробела между строкой и значением

2021-09-23 09:03 UTC, romer533 commented on src/CharAriDemo.java
> +    public static void main(String args[]){
`String[] args`

2021-09-23 09:03 UTC, romer533 requested changes
Need to fix

2021-09-23 09:05 UTC, romer533 commented
Правильно название для ветки: `char_ari_demo`

2021-09-23 09:07 UTC, romer533 commented
И не забудь прошлый МР испарвить, я тебе там накидал всего, ты не проработала
Можешь прям в рамках этого МР исправить
И новые замечания тоже проработай

2021-09-25 13:47 UTC, VasilevaVeronika commented on src/CharAriDemo.java
> +        System.out.println("теперь ch содержит" + ch);
Fixed

2021-09-25 13:48 UTC, VasilevaVeronika commented on src/CharAriDemo.java
> +        System.out.println("теперь ch содержит" + ch);
Fixed

2021-09-25 13:48 UTC, VasilevaVeronika commented on src/CharAriDemo.java
> +        System.out.println("теперь ch содержит" + ch);
Fixed

2021-09-25 13:48 UTC, VasilevaVeronika commented on src/CharAriDemo.java
> +    public static void main(String args[]){
Fixed

2021-09-27 12:55 UTC, merged