Create sound.java
VasilevaVeronika/java-learning pull request #8
Opened 2021-09-28 13:57 UTC by VasilevaVeronika

2021-09-28 14:09 UTC, romer533 requested changes
Needs to be fixed, but first merge my branch and merge it here

2021-09-28 14:09 UTC, romer533 commented on src/com/veronika/sound.java
> +        System.out.println("Расстояние до менста вспышки молнии " + " составляет " + dist + " футов");
Менста

2021-09-28 14:09 UTC, romer533 commented on src/com/veronika/sound.java
> +package com.veronika;
Не правильный package

2021-09-28 14:34 UTC, romer533 commented on src/com/veronika/sound.java
> +public class sound {
Invalid name for class

2021-09-28 14:58 UTC, VasilevaVeronika commented on src/com/veronika/sound.java
> +        System.out.println("Расстояние до менста вспышки молнии " + " составляет " + dist + " футов");
fixed

2021-09-28 14:59 UTC, VasilevaVeronika commented on src/com/veronika/sound.java
> +package com.veronika;
fixed

2021-09-28 14:59 UTC, VasilevaVeronika commented on src/com/veronika/sound.java
> +public class sound {
fixed

2021-09-28 15:10 UTC, romer533 requested changes
Needs to fix

2021-09-28 15:10 UTC, romer533 commented on src/com/veronika/part_2/sound.java
> +import static java.lang.System.out;
Это еще что такое

2021-09-28 15:22 UTC, romer533 commented on src/com/veronika/part_2/sound.java
> +
Добавь комментарий выше названия класса, что это упражнение, а не просто код из книжки
`// Упражнение 2.1`

2021-09-28 15:35 UTC, VasilevaVeronika commented on src/com/veronika/sound.java
> +
fixed feet per meter

2021-09-28 15:36 UTC, VasilevaVeronika commented on src/com/veronika/sound.java
> +        System.out.println("Расстояние до менста вспышки молнии " + " составляет " + dist + " футов");
fixed

2021-09-28 15:36 UTC, VasilevaVeronika commented on src/com/veronika/sound.java
> +    }
fixed

2021-09-28 15:37 UTC, VasilevaVeronika commented on src/com/veronika/part_2/sound.java
> +
exercise added

2021-09-28 15:52 UTC, romer533 requested changes
Not today

2021-09-28 15:52 UTC, romer533 commented on src/com/veronika/part_2/sound.java
> +// Упражнение 2.1
Обязательно пустые строк после package и желательно перед названием класса

2021-09-28 15:52 UTC, romer533 commented on src/com/veronika/part_2/sound.java
> +        double distanceInMeters = 330 * 7.2;
Я разве сказал убрать dist?

2021-09-28 15:52 UTC, romer533 commented on src/com/veronika/part_2/sound.java
> +        System.out.println("Расстояние до места вспышки молнии составляет " + distanceInMeters + " метров");
Я разве сказал убрать dist?

2021-09-28 16:24 UTC, VasilevaVeronika commented on src/com/veronika/part_2/sound.java
> +// Упражнение 2.1
added

2021-09-28 16:32 UTC, romer533 requested changes
Need to fix

2021-09-28 16:32 UTC, romer533 commented on src/com/veronika/part_2/sound.java
> +        double distanceInMeters = 330 * 7.2;
Нарушена структура приложения:
В самом верху должны быть объявлены переменные:
```
double dist, distanceInMeters;
```
затем нужно проинициализировать переменные:
```
dist = ???;
distanceInMeters = ???;
```
И только потом исполняющий код
```
Sout(???);
Sout(???);
```

2021-09-28 16:39 UTC, romer533 commented
Мое решение этой задачи:
![image](https://user-images.githubusercontent.com/24517447/135129354-cae1fd20-577c-4a93-901c-04b13606fba0.png)
P.S. можно лучше

2021-10-01 14:45 UTC, romer533 requested changes

2021-10-01 14:45 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        dist2 = 446 / 6;
Не говорящее название

2021-10-01 14:45 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        distanceInMeters2 = 136 / 2;
Не говорящее название

2021-10-01 14:45 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        dist2 = 446 / 6;
Что это за цифры?
От куда они взялись?

2021-10-01 14:45 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        distanceInMeters2 = 136 / 2;
Что это за цифры?
От куда они взялись?

2021-10-01 15:38 UTC, romer533 requested changes

2021-10-01 15:38 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        soundInFeet = 10.210 * 181.97 / 2;
Что за числа с головы?

2021-10-01 15:38 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        soundInMeters = 335 * 5.97;
Не правильно

2021-10-01 15:38 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        System.out.println("Расстояние до месторасположения горы " + soundInFeet + " футов");
Ответ не верный

2021-10-01 15:38 UTC, romer533 commented on src/com/veronika/part_2/Sound.java
> +        System.out.println("Расстояние до месторасположения горы " + soundInMeters + " метров");
Ответ не верный

2021-10-01 15:56 UTC, romer533 approved these changes

2021-10-01 15:58 UTC, merged